# Generated by Django 5.1.2 on 2024-10-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Allo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AlloNum", models.CharField(max_length=10, verbose_name="调配基准编号")),
                ("AlloID", models.CharField(max_length=10, verbose_name="调配配区代码")),
                ("ParID", models.CharField(max_length=20, verbose_name="父物料号")),
                ("ParName", models.CharField(max_length=20, verbose_name="父物料名称")),
                ("ChiID", models.CharField(max_length=20, verbose_name="子物料号")),
                ("ChiName", models.CharField(max_length=20, verbose_name="子物料名称")),
                ("ConnNum", models.IntegerField(verbose_name="子物料数量")),
                ("MatPre", models.IntegerField(verbose_name="物料提前期")),
                ("ShoPre", models.IntegerField(verbose_name="供应商提前期")),
            ],
        ),
        migrations.CreateModel(
            name="BOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MatID", models.CharField(max_length=5, verbose_name="物料号")),
                ("MatName", models.CharField(max_length=20, verbose_name="名称")),
                ("MatNeed", models.IntegerField(verbose_name="装配数量")),
                ("MatUni", models.CharField(max_length=4, verbose_name="单位")),
                ("MatCen", models.CharField(max_length=1, verbose_name="层次")),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "MatID",
                    models.CharField(max_length=5, unique=True, verbose_name="物料号"),
                ),
                ("MatName", models.CharField(max_length=20, verbose_name="名称")),
                ("MatUni", models.CharField(max_length=4, verbose_name="单位")),
                ("MatPro", models.CharField(max_length=10, verbose_name="调配方式")),
                ("MatLos", models.FloatField(verbose_name="损耗率")),
                ("MatPre", models.FloatField(verbose_name="提前期")),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "MatID",
                    models.CharField(max_length=5, unique=True, verbose_name="物料号"),
                ),
                ("MatName", models.CharField(max_length=20, verbose_name="名称")),
                ("MatRem", models.IntegerField(verbose_name="工厂库存")),
                ("MatPre", models.IntegerField(verbose_name="资料库存")),
            ],
        ),
    ]
